[package]
name = "bloom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10.7"
sha1 = "0.10.6"
sha2 = "0.10.8"
